steps:
  # Create a step that builds the "base" Docker image
  # The base Docker image should be tagged with ${BUILD_ID} and `latest`.
  - name: "gcr.io/cloud-builders/docker" # Tells Cloudbuild that this step involves Docker
    id: # Give me a unique name that describes this step
    args:
      # A list of arguments to provide to the `docker` command.
      # Eg. calling `docker build --tag foo:${BUILD_ID} --tag foo:latest -f Dockerfile .` would look like
      # args:
      #   - build
      #   - --tag
      #   - foo:${BUILD_ID} # Example of a substitution
      #   - --tag
      #   - foo:latest
      #   - -f
      #   - Dockerfile.base
      #   - .
  
  # Create a step that pushes the "base" Docker image to the Artifact registry
  # with the tag ${BUILD_ID}
  - name: "gcr.io/cloud-builders/docker"
    id: # Give me a unique name that describes this step.
    args:
      # Here we will want to invoke the `push` command.
      # eg. push IMAGE:TAG

  # Create a step that pushes the "base" Docker image to the Artifact registry
  # with the tag `latest`.
  - name: "gcr.io/cloud-builders/docker"
    id: # Give me a unique name that describes this step.
    args:
      # Here we will want to invoke the `push` command.
      # eg. push IMAGE:TAG

  # Create a step that builds the "target" Docker image
  # (could be frontend_v1, frontend_v2, backend_v1 or backend_v2).
  - name: "gcr.io/cloud-builders/docker"
    id: # Give me a unique name that describes this step.
    args:
      # A list of arguments to provide to the `docker` command.
      # Tag the image ONLY with the ${BUILD_ID}

  # Create a step that pushes this Docker image to the Artifact Registry.
  # Make sure it has a different name than the base image, frontend and/or backend.
  - name: "gcr.io/cloud-builders/docker"
    # And so on...
substitutions:
    _APP_URI: required
    _BASE_IMAGE_URI: required
    _SERVING_PORT: required
    _TARGET_DOCKERFILE: required
options:
    substitutionOption: 'ALLOW_LOOSE'